- examples/cosmic/src/main.rs
- src/widget/mod.rs
- src/widget/nav.rs
- src/widget/scrollable.rs
- Swapped `iced::widget::scrollable` with `cosmic::scrollable` in existing widgets.
- Renamed macro from `scrollbar` to `scrollable`
> Renamed custom scrollable widget

- Cargo.toml
- examples/cosmic/src/window.rs
- src/lib.rs
- src/theme/expander.rs
- src/theme/mod.rs
- src/theme/palette.rs
- src/widget/expander.rs
- src/widget/header_bar.rs
- src/widget/list/list_box.rs
- src/widget/list/macros.rs
- src/widget/navigation/macros.rs
- src/widget/navigation/navbar.rs
I think it's best to only include things in the Iced fork that can't be done without forking Iced, and/or are expected to be merged upstream. The theme doesn't seem to be either, so it fits more appropriately in libcosmic.
That should make it easier to keep up with upstream, and it may help to have all the Cosmic parts in one place.
Based on https://github.com/pop-os/iced commit ad9026e.
> Include Cosmic theme in libcosmic, instead of in Iced fork

- Cargo.toml
- examples/cosmic-sctk/Cargo.toml
This updates iced to the latest version that moves iced_sctk back into pop-os/iced. It also tweaks the features and dependencies a bit
> update: iced & some deps

- Cargo.toml
This allows applets to use the `time::every` subscription
I need it for the cosmic time applet.
> Add tokio fieature to iced import

- src/applet/mod.rs
Just a simple helper function for applets with a size that isn't a single icon & `rustfmt`
Required to fix the iced clock applet
> CosmicAppletHelper: Add window size helper

- .gitmodules
- Cargo.toml
update freedesktop-icons & change iced submodule branch to master.
Auto-sized surfaces are currently only auto-sized on creation but I have a plan to make them resize whenever necessary within the provided limits.
> feat: autosized surface support

- Cargo.toml
- examples/cosmic/src/window.rs
- examples/cosmic/src/window/demo.rs
- src/theme/mod.rs
- src/widget/mod.rs
- src/widget/segmented_button/mod.rs
- src/widget/segmented_button/state.rs
- src/widget/segmented_button/style.rs
We may now implement tabbed interfaces, complete with a stylesheet implementation.
Based on
Improvement still to come to style the mouse hover over a button, implementing different style variants, and a multi-select mode.
> feat: implement SegmentedButton widget

- examples/cosmic/src/window.rs
- examples/cosmic/src/window/demo.rs
- src/theme/mod.rs
- src/widget/segmented_button/cosmic.rs
- src/widget/segmented_button/mod.rs
- src/widget/segmented_button/state.rs
- src/widget/segmented_button/style.rs
- Adds support for tracking the hover state to apply a hover style to hovered tabs.
- Renames the default style to `ViewSwitcher` to make room for an alternative `Selection` style.
- Border radius style now configurable based on position of widget in the view.
- The background and border of the entire widget is now also themable.
- Adds `font_active`, `font_hovered`, and `font_inactive` methods to `SegmentedButton` for configuring the fonts.
- Adds cosmic-specific functions for constructing a `view_switcher` and `segmented_selection` with ideal COSMIC theming and setup. Such as specifying a semi-bold font for active buttons or preferred default heights.
[SegmentedButton.webm](https://user-images.githubusercontent.com/4143535/209882257-2b1421da-7f04-44f2-a17d-edf09505649f.webm)
> Improvements to the Segmented Button widget

- Cargo.toml
- examples/cosmic/Cargo.toml
- examples/cosmic/src/window.rs
- examples/cosmic/src/window/bluetooth.rs
- examples/cosmic/src/window/demo.rs
- examples/cosmic/src/window/desktop.rs
- examples/cosmic/src/window/system_and_accounts.rs
- src/theme/mod.rs
- src/widget/mod.rs
- src/widget/segmented_button/cosmic.rs
- src/widget/segmented_button/mod.rs
- src/widget/segmented_button/state.rs
- src/widget/segmented_button/style.rs
- Adds `Orientation` enum for defining the vertical or horizontal layout of a widget.
- Implements vertical orientation for the segmented button widget and its cosmic styles.
- cosmic pages now have their own states and messages, and all controls are now mapped to unique states
> Vertical layout for segmented buttons, and cosmic example improvements

- examples/cosmic-sctk/src/main.rs
- examples/cosmic/src/main.rs
- examples/cosmic/src/window.rs
- examples/cosmic/src/window/demo.rs
- src/lib.rs
- src/settings.rs
- src/widget/icon.rs
- src/widget/spin_button/mod.rs
Applications may now override the default icon theme application-wide using a new convenience function. Typically called before running the application.
```rs
cosmic::settings::set_default_icon_theme("Pop");
```
It can be applied at any moment during the lifetime of the application. The cosmic example has been updated to demonstrate the ability to dynamically switch between loading icons from the Pop and Adwaita themes. Ideally we'll want to support loading this setting from a configuration file of some kind, too.
Closes #61
> Global setting for default icon theme

- src/widget/header_bar.rs
Allows the `HeaderBar` widget to be allocated with a `'static` lifetime while still using the `title`-setter by passing in an owned `String`.
> widget/headerbar: Allow owned string

- .github/workflows/ci.yml
This adds the feature set cosmic-comp uses for libcosmic to the CI feature matrix, to avoid breaking compiling without a shell feature enabled.
Recently the keyboard_nav-widget broke this, which is why this also updates iced to include https://github.com/pop-os/iced/pull/25.
> ci: Test variant without shell

- Cargo.toml
- src/lib.rs
- src/single_thread_executor.rs
At least for applets, this is probably better than spawning a tokio worker thread per CPU thread.
> Add tokio-based `SingleThreadExecutor`

- Cargo.toml
this updates iced with dyrend support and removes glow support from iced-sctk for now. Softbuffer is by default the only enabled renderer in dyrend for now.
> feat: dyrend

- examples/cosmic/Cargo.toml
- examples/cosmic/src/window.rs
- examples/cosmic/src/window/editor.rs
- src/widget/icon.rs
- src/widget/nav_bar.rs
- src/widget/segmented_button/mod.rs
- src/widget/segmented_button/model/builder.rs
- src/widget/segmented_button/model/entity.rs
- src/widget/segmented_button/model/mod.rs
- src/widget/segmented_button/model/selection.rs
- src/widget/segmented_button/widget.rs
These changes extend the functionality of the segmented button widget to support optional and configurable use of close icons which can emit close messages on click. As well as making it possible to override the default color assigned to an item's icon.
An example is also included, and the `IconSource` enum is refactored to unify the `Embedded` and `EmbeddedSvg` variants as a `Handle` variant, using the existing `icon::Handle` enum.
---
Adds support for displaying and handling tab closes, as well as displaying the close icon only on tabs which are hovered or active.
```rs
view_switcher::horizontal(&app.tabs)
.show_close_icon_on_hover(true)
.on_activate(Message::TabActivate)
.on_close(Message::TabClose)
```
Items will display a close icon only if the closable property is set.
```rs
let id …
```
> Configurable close icons for view switching

- Cargo.toml
- cosmic-config/Cargo.toml
- cosmic-config/src/lib.rs
- examples/config/Cargo.toml
- examples/config/src/main.rs
This adds the Config API as discussed on Pop!_OS chat. The API backend details are abstracted and should be reviewed separately from the frontend.
Tested on Linux, macOS, and Windows. Windows required patching out the use of `freedesktop-icons`, we may want to offer an alternative to that.
> Config API

- Cargo.toml
- src/widget/icon.rs
We'll need libcosmic to work on Windows and macOS if we want to use it in the Keyboard Configurator.
`freedesktop-icons` doesn't seem to build on Windows, so only use it on Unix systems. It does seem to build on macOS, so leave it as a dependency there. A good solution for icon bundling on macOS/Windows will need to be figured out at some point.
> Fix build on Windows/non-Unix

- examples/cosmic/src/window.rs
- src/applet/mod.rs
- src/theme/expander.rs
- src/theme/mod.rs
- src/theme/segmented_button.rs
- src/widget/icon.rs
- src/widget/list/column.rs
- src/widget/nav_bar.rs
- src/widget/search/field.rs
- src/widget/spin_button/mod.rs
- src/widget/warning.rs
This is more general, and necessary if the custom theming is dynamically generated.
Iced's builtin theme also uses `Box`ed `Fn`, or `Rc` where clone is required, so this seems reasonable.
Only `Text` is left using `fn`, since it needs to be `Copy`. Hopefully that can be changed in Iced at some point.
`::custom` methods are added to make these variants a little more convenient to construct. This replaces a couple `From` implementations, which are potentially problematic with a generic.
> theme: Use boxed functions instead `fn` pointers

- cosmic-config/Cargo.toml
- cosmic-config/src/calloop.rs
- cosmic-config/src/lib.rs
This should be useful for integrating cosmic-config into things using calloop, like cosmic-comp.
> config: Add `calloop` feature to provide a calloop source

- Cargo.toml
- src/lib.rs
This allows cosmic-time to use all imports via libcosmic, so the versions of iced will not collide.
For https://github.com/pop-os/cosmic-time/pull/12
> Expose internal iced crates for cosmic-time

- cosmic-config/Cargo.toml
In combination with https://github.com/pop-os/iced/pull/43 this drops cosmic-configs dependencies even when using subscriptions.
> cosmic-config: Don't pull all of iced's dependencies

- examples/cosmic/src/window/demo.rs
- src/widget/icon.rs
- src/widget/segmented_button/widget.rs
This makes icon lookup search for default fallbacks on failure, found by shortening the icon name at ‘-‘ characters.
> feat: icon default fallbacks

- src/app/settings.rs
Since these don't default to `None`, and the fields aren't public, using `strip_option` makes it impossible to change them to `None`.
> app/settings: Don't use `strip_option`

- Cargo.toml
- cosmic-theme/src/model/theme.rs
- src/app/applet/mod.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
This seems to address the issues from https://github.com/pop-os/cosmic-applets/pull/110 but maybe a separate trait could be added which adds the style by default.
> wip: add applet module

- src/app/settings.rs
Uses manual implementation for setting the icon theme so that an empty string is treated as `None`.
Fixes this error message in the application example
```sh
error[E0277]: the trait bound `Option<String>: From<&str>` is not satisfied
--> examples/application/src/main.rs:24:29
|
24 |         .default_icon_theme("Pop")
|          ------------------ ^^^^^^^^^ the trait `From<&str>` is not implemented for `Option<String>`
|          |
|          required by a bound introduced by this call
```
> Fix derive setter for default_icon_theme.

- src/app/applet/mod.rs
With the default size limit, autosize applets don't work as expected. Setting this to `None` seems to work fairly well, though maybe we'll need to tune some of these settings more later.
> app/applet: set `size_limits` to `None` for `autosize`

- src/app/mod.rs
- src/app/settings.rs
This adds a setting for disabling the main window. It is useful for the app library, launcher and similar apps.
> feat: allow creating apps with no main window on wayland

- examples/application/Cargo.toml
- examples/application/src/main.rs
- src/command/mod.rs
- src/lib.rs
- src/widget/mod.rs
This will enable the window drag feature to work when clicking and dragging the headerbar in an libcosmic application using the Application trait. The default feature for the application example is now `winit`. Although usable in Wayland, window drag and resize does not work in Wayland since it's not supported by winit right now.
> fix(app): draggable windows on X11 systems using winit

- src/app/settings.rs
- src/icon_theme.rs
This would default to using icons from https://github.com/pop-os/cosmic-icons
> refactor: default the icon theme to Cosmic

- src/widget/button/mod.rs
Replaces existing setters with derived setters, and allows the deriver_setters macro to generate setters for more properties.
> feat(widget): make public more button builder properties

- Cargo.toml
0.2.3 and 0.2.4 contain a bunch of fixes to the icon lookup functions. Make sure we are always using the latest version.
> chore: Update freedesktop-icons

- examples/cosmic/src/window/demo.rs
- src/widget/text_input/input.rs
App library has regular text inputs that can be cleared.
> refactor: allow text input on_clear for more than just search_input

- .github/workflows/ci.yml
- cosmic-config/Cargo.toml
- src/lib.rs
Update calloop for compatibility with latest smithay
EDIT:
- Now based on https://github.com/pop-os/libcosmic/pull/174
- Updated iced to include https://github.com/pop-os/iced/pull/65
- Allow compiling without any windowing system features
> chore: Update calloop

- cosmic-config/src/lib.rs
- examples/config/src/main.rs
This will allow cosmic-bg to store the latest background state per output, for the lock screen and cosmic-settings to pick up.
> cosmic-config: Add new_state constructor for storing state

- Cargo.toml
- cosmic-config/src/lib.rs
- examples/application/src/main.rs
- examples/config/src/main.rs
- examples/open-dialog/src/main.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/theme/style/button.rs
- src/widget/context_drawer/mod.rs
- src/widget/context_drawer/overlay.rs
- src/widget/context_drawer/widget.rs
- src/widget/grid/layout.rs
- src/widget/grid/mod.rs
- src/widget/grid/widget.rs
- src/widget/mod.rs
- src/widget/navigation.rs
- src/widget/rectangle_tracker/mod.rs
In addition to implementing the `ContextDrawer` widget, this adds a `Application::context_drawer` method for constructing the view of the context bar, which should be shown when `Core.window.show_context` is set to `true`.  The `ApplicationExt` trait also now has `set_context_title` and `set_header_title` methods. Whereas `ApplicationExt::set_title` has been renamed to `set_window_title`.
cosmic-design-demo PR: https://github.com/pop-os/cosmic-design-demo/pull/3
After merging the cosmic-design-demo PR, it should be updated here as well.
> Add ContextDrawer widget

- Cargo.toml
- cosmic-config-derive/src/lib.rs
- cosmic-config/src/lib.rs
- cosmic-theme/Cargo.toml
- cosmic-theme/src/model/cosmic_palette.rs
- cosmic-theme/src/model/dark.ron
- cosmic-theme/src/model/light.ron
- cosmic-theme/src/model/mod.rs
- cosmic-theme/src/model/mode.rs
- cosmic-theme/src/model/theme.rs
- examples/cosmic/src/window/demo.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/theme/mod.rs
- src/theme/style/iced.rs
- src/widget/color_picker/mod.rs
- src/widget/settings/item.rs
Also adds support for custom light / dark mode themes.
> feat: add support for dark / light mode switching

- cosmic-theme/src/model/derivation.rs
- cosmic-theme/src/model/theme.rs
Also, If the button is transparent, uses the overlay directly for hover and pressed states.
> fix: match the button overlays with figma

- examples/image-button/Cargo.toml
- examples/image-button/src/main.rs
- src/theme/style/button.rs
- src/widget/button/image.rs
- src/widget/button/mod.rs
- src/widget/button/text.rs
- src/widget/button/widget.rs
- src/widget/header_bar.rs
- src/widget/icon/mod.rs
A button which is rendered as a bordered image with a 3:2 aspect ratio. The enabled state displays a checkmark in the lower left corner.
> Add ImageButton widget variant

- examples/image-button/src/main.rs
- src/theme/style/button.rs
- src/widget/button/image.rs
- src/widget/button/mod.rs
- src/widget/button/widget.rs
This is one of the feature additions required for the wallpaper settings page.
- Adds an optional removable button overlay to the image button widget.
- Refactors image button logic in the button widget implementation.
- Selects the proper background color for the selection indicator and close button
- Updates `cosmic-image-button` example to showcase removable image buttons
> feat(image_button): add optional removable button overlay

- src/app/cosmic.rs
- src/app/mod.rs
A Cosmic application has no way to call `Cosmic<T>::close` to set the `should_exit` flag there, as far as I'm aware.
So it makes sense to add a `should_exit` method here.
> Add a `should_exit` method to `Application` trait

- src/widget/icon/named.rs
This fixes compilation for Windows, where freedesktop_icons::lookup is not available. In the future, we could consider a feature to bundle some icons with libcosmic for Windows and macOS, and also have an os-agnostic way to get icons for a mime type.
> Fix compilation on Windows

- Cargo.toml
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/app/settings.rs
- src/applet/mod.rs
- src/applet/token/mod.rs
- src/applet/token/subscription.rs
- src/applet/token/wayland_handler.rs
- src/lib.rs
- src/process.rs
- src/widget/text_input/input.rs
This implements org.freedesktop.Application for cosmic apps.
> wip: dbus activation & single instance support

- src/widget/popover.rs
This will be used temporarily for cosmic-edit context menu. In the future I'd like to re-use the menu bar code.
> Allow custom position in popover

- examples/cosmic/Cargo.toml
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/app/settings.rs
This is a refactor of the single instance / dbus activation implementation that makes the feature purely additive. It does add a generic parameter to Core, but I'm not sure of a better way of requiring it in `run_single_instance` while keeping `single-instance` feature additive.
> refactor: make the single-instance feature additive

- Cargo.toml
- src/widget/grid/layout.rs
Also adds `rev =` to `Cargo.toml` specifying the latest commit.
A library like `libcosmic` shouldn't use git dependencies without specifying a commit or tag.
> Fix compilation with latest `taffy` commit

- Cargo.toml
This fixes cosmic-edit build on Windows
> Make ashpd optional when using tokio feature

- src/theme/style/dropdown.rs
- src/widget/dropdown/menu/appearance.rs
- src/widget/dropdown/mod.rs
- src/widget/dropdown/multi/menu.rs
- src/widget/dropdown/multi/mod.rs
- src/widget/dropdown/multi/model.rs
- src/widget/dropdown/multi/widget.rs
Needed for the cosmic-settings wallpaper page, where there are some hardcoded options alongside a separate "Recent Folders" category. PRs for cosmic-settings and the design demo will come after merge.
> feat(widget): add `dropdown::multi` list widget

- src/widget/dropdown/multi/menu.rs
- src/widget/dropdown/multi/widget.rs
Fixes a panic affecting the updated wallpaper settings page when rebased to the new version. Also fixes some layout and drawing issues with the rebase.
> Fix panic and layout issues in `dropdown::multi` widget

- examples/cosmic/Cargo.toml
- src/applet/mod.rs
- src/theme/style/dropdown.rs
- src/theme/style/iced.rs
- src/theme/style/segmented_button.rs
- src/widget/button/style.rs
- src/widget/button/widget.rs
- src/widget/context_drawer/widget.rs
- src/widget/list/mod.rs
- src/widget/nav_bar.rs
- src/widget/search/field.rs
- src/widget/segmented_button/widget.rs
- src/widget/text_input/input.rs
- src/widget/warning.rs
Not all values matched a default value but I picked the next closest in that case. Lots went from 2 -> 4 and 24 -> 16 as a result. Some applications also need to be updated because they sometimes will have a hard-coded border radius.
> refactor: use theme corner radii everywhere

- src/widget/flex_row/layout.rs
This will fix certain window widths causing the wallpaper selection view to display one extra widget on the first row.
> fix(flex-row): awkward breakpoint after first row

- src/app/core.rs
- src/app/mod.rs
This allows the terminal to use transparency.
> Add content_container flag to enable/disable wrapping content

- src/widget/menu/menu_bar.rs
Whitout this, i get this error when compiling application example and multi-window:
```
error: casting `&T` to `&mut T` is undefined behavior, even if the reference is unused, consider instead using an `UnsafeCell`
--> src\widget\menu\menu_bar.rs:231:34
|
229 | ...dget_ptr_mut = widget_ptr as *mut dyn Widget<Message, Renderer>;    
|                   ------------------------------------------------ casting happend here
230 | ...: find a way to diff_children without unsafe code
231 | ... { &mut *widget_ptr_mut }
|       ^^^^^^^^^^^^^^^^^^^^
|
= note: for more information, visit <https://doc.rust-lang.org/book/ch15-05-interior-mutability.html>
= note: even for types with interior mutability, the only legal way to obtain a mutable pointer from a shared reference is through `UnsafeCell::get` …
```
> Fix invalid_reference_casting

- src/widget/popover.rs
This keeps the popup inside the parent widget bounds, logic that is common for context menus
> widget::popover: context menu positioning logic

- src/app/cosmic.rs
- src/app/mod.rs
This is important to properly manage focus.
> Allow apps to return a command when context drawer is toggled

- src/widget/header_bar.rs
This allows for the center widget to expand beyond one third of the header bar
> widget/header_bar: shrink start and end

- cosmic-config-derive/src/lib.rs
- cosmic-config/src/lib.rs
- cosmic-theme/src/model/mode.rs
- fixes issue where transaction was not being used for write_entry
- generates set_field_name setters that can be used to set the value of one key and only write to disk if it changed
- pretty prints config file data
> Config improvements

- .github/workflows/pages.yml
This makes my life easier so I don't have to keep running `cargo doc --open`
> Generate documentation and publish to github pages

- cosmic-config/src/dbus.rs
- cosmic-config/src/lib.rs
- cosmic-config/src/subscription.rs
- examples/applet/src/window.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/theme/mod.rs
This simplifies watching configs and should also improve error handling by indicating which key failed to be retrieved. I'm not sure I like using `block_on` when connecting to the settings daemon but it avoids restarting the subscriptions.
> refactor: config improvements

- Cargo.toml
- examples/open-dialog/Cargo.toml
- examples/open-dialog/src/main.rs
- justfile
- src/dialog/file_chooser/mod.rs
- src/dialog/file_chooser/open.rs
- src/dialog/file_chooser/save.rs
- src/dialog/mod.rs
- src/lib.rs
- Sorts dependencies and features alphabetically
- Re-exports ashpd from the dialog module for increased visibility of portal dialog options
- The file_chooser dialog no longer requires a subscription
- The file_chooser dialogs now provide `open_file`, `open_files`, `open_folder`, `open_folders`, and `save_file` methods
- Creates `Error::Cancelled` when a dialog is cancelled
- Adds `rfd` feature that implements the file_chooser with rfd over ashpd
- Some features are not supported by `rfd`, such as choices, glob/mimetype filters, modal, and accept_label; or files that are selected from non-file paths
> feat!(dialog): refactor and support rfd as file_chooser provider

- src/widget/segmented_button/horizontal.rs
- src/widget/segmented_button/vertical.rs
- src/widget/segmented_button/widget.rs
- Text will now be clipped at the proper bounds to prevent overlapping with the close button
- Pagination feature
- Horizontal segmented buttons may now paginate their items if the width of the widget is too narrow.
- When paginated, there will be a prev and next tab button surrounding the buttons
- The focus logic has been updated to support focusing and activating the prev and next tab buttons with keyboard navigation
- A new property, `minimum_button_width`, will configure when buttons will begin to paginate
> Paginate tabs in horizontal view switcher when tabs too narrow

- cosmic-config/Cargo.toml
- cosmic-config/src/lib.rs
This commit changes the hardcoded /usr/share paths in cosmic-config to become performed via XDG lookups using the `xdg` crate.
This allows the installed files to be discovered on non-FHS Linux, e.g. NixOS.
Hardcoded /var/lib/ is removed entirely because
1. nothing installs to it yet (only user of new_state is cosmic_bg currently and it does not install to /var/lib)
2. it's intended for system states, not template for user state.
3. it's not part of XDG spec.
> Remove hardcoded paths in cosmic-config

- src/widget/segmented_button/horizontal.rs
- src/widget/segmented_button/vertical.rs
- src/widget/segmented_button/widget.rs
Once this is merged, I will make PRs for cosmic-edit and cosmic-term to utilize the new features.
When the width of a horizontal segmented button is set to `Shrink`:
- Enable variable width button widths
- Supports tab pagination when there is too little space
Also makes the following improvements:
- Drawing should now require less CPU
- Fix for drawing in vertical layout
Remaining issues to resolve
- Integrate better with a tab add button
- Fix overlapping layout when `Fill` width when pagination is enabled
> segmented_button: support variable-width buttons when horizontal width is `Shrink`

- Cargo.toml
- src/desktop.rs
- src/lib.rs
This is an attempt at unifying implementations of this across `cosmic-applibrary`, `cosmic-launcher`, `cosmic-app-list` (in cosmic-applets) and soon `cosmic-store`.
This is mostly based on the app-list implementation, as that parses most of the desktop files contents. Particular attention was given to allow for all the different filtering these apps do, as well as to easy icon handling. Additionally contains code necessary for handling gpu selection in the future (`prefers_dgpu` and explicitly setting a `wayland_display` for the spawn method).
This is just doing code deduplication and cleanup, the goal is not e.g. to do complete `exec` parsing in this PR.
I'll keep this as a draft until I have written proper implementations against all our use-cases, but in principle this is ready for …
> libcosmic: Add desktop-file helpers

- examples/cosmic/Cargo.toml
Update to include https://github.com/pop-os/iced/pull/98.
> Update iced submodule

- examples/cosmic/Cargo.toml
- examples/cosmic/src/window/demo.rs
- src/widget/segmented_button/widget.rs
This is needed for the new tiling applet. Transparent text only seems to be working with the wgpu feature at the moment
> feat: lower the opacity of colors used in the segmented button when disabled

- src/app/cosmic.rs
- src/app/mod.rs
- src/widget/header_bar.rs
With this, apps like cosmic-term require no changes to show the compositor window menu when the header is right clicked.
Requires https://github.com/pop-os/iced/pull/103.
> header_bar: Show window menu on right click

- src/desktop.rs
May require adaptation by programs that use the categories (the app library, cc @wash2)
> fix(desktop): split categories by semi-colon terminator

- cosmic-theme/src/model/derivation.rs
- cosmic-theme/src/model/theme.rs
- src/theme/mod.rs
- src/theme/style/iced.rs
- src/widget/context_drawer/widget.rs
- src/widget/list/mod.rs
- src/widget/settings/item.rs
- Moves custom config styles for `List` and `ContextDrawer` to our `Container` style
- Fixes dark list containers in the context drawer on the light theme
- Applies clippy lints to the derivaion module in cosmic-theme
- Groups and reorganizes the background, primary, and secondary container code so that they're easier to debug
- Adds methods for creating default appearances for background, primary, and secondary containers
The fix for the context drawer on light themes is a workaround until we can figure out why the primary container component has such as a dark background color with the light theme.
Closes #314
> Theme refactoring and improvements

- .vscode/settings.json
This was needed for me to get autocomplete with rust-analyzer for libcosmic. If this isn't the right way to do it, vscode suggested it, don't kill the messenger!
> fix: include Cargo.toml in .vscode/settings.json

- cosmic-config-derive/src/lib.rs
Fixes logged errors in cosmic-settings when the config files are not created yet.
> fix(cosmic-config-derive): do not return error when getting config which is not set

- src/desktop.rs
This PR adds a "name" fallback and changes the startup_wm_class fallback to evaluate independent of case.
Some applications (like element desktop) have a app id capitalized e.g. "Element" when their startup_wm_class is lowercase e.g. "element".
The "name" fallback is separate from the startup_wm_class and appid conditions just in case an app is named something similar to another app's id.
Apps known by me to be fixed by the case insensitive wm_class fallback:
* Element
* RStudio
* Steam
* VLC
Apps known by me to be fixed by the name fallback:
* ONLYOFFICE Desktop Editors
This should fix part (or potentially all) of [this issue](https://github.com/pop-os/cosmic-applets/issues/194), [this issue](https://github.com/pop-os/cosmic-applets/issues/195), and [this …
> fix: add case independent startup_wm_class, name fallback

- examples/cosmic/src/window.rs
- examples/multi-window/src/window.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/theme/style/button.rs
- src/widget/button/icon.rs
- src/widget/button/style.rs
- src/widget/button/widget.rs
- src/widget/color_picker/mod.rs
- src/widget/header_bar.rs
Headerbar icons are transparent when their window is not focused, but otherwise share the same style as icons with selection. This updates the icon styles to match figma when selected. Though, it doesn't seem like transparent icons are drawn as transparent at the moment.
> refactor: icon styling and headerbar icon styling

- src/desktop.rs
This will ideally be used with cosmic-applets to have a libcosmic friendly way to determine app id matches, including fallbacks.
Part of how to fix: https://github.com/pop-os/cosmic-applets/issues/278
After this PR is merged, the cosmic-applets PR can be merged, provided libcosmic is bumped to the new commit
> feat: add public function to determine app id matches

- src/widget/layer_container.rs
- src/widget/mod.rs
Makes it available as `cosmic::widget::layer_container()`. @edfloreshz
> refactor: rename `cosmic_container` to `layer_container`

- examples/menu/Cargo.toml
- examples/menu/src/main.rs
- src/widget/menu.rs
- src/widget/menu/action.rs
- src/widget/menu/key_bind.rs
- src/widget/menu/menu_tree.rs
This PR simplifies the menu declaration for cosmic applications.
It is not longer required that the user builds each widget for the menu, it is now possible to construct the necessary widgets based on user input, applying a standard style to all menus across applications.
```rust
MenuBar::new(vec![MenuTree::with_children(
menu_root("File"),
menu_items(
key_binds,
vec![
MenuItem::Action("New window", Action::WindowNew),
MenuItem::Separator,
MenuItem::Action("Quit", Action::WindowClose),
],
),
)])
```
- Added `MenuAction` trait to call the `message` method on button press.
- Added two new methods to construct a `MenuTree`.
- Added `MenuItem` enum to represent an action or a separator in a `MenuTree`.
- Added menu example.
- Moved `Modifier` enum and `KeyBind` struct to libcosmic.
- Moved …
> improv(menu): simplify menu construction.

- examples/menu/src/main.rs
- src/widget/menu/menu_tree.rs
This PR adds support for two more menu item types, `checkbox` and `folder`, this should allow [`cosmic-edit`](https://github.com/pop-os/cosmic-edit) and [`cosmic-term`](https://github.com/pop-os/cosmic-term) to adopt `MenuItem`.
```rust
MenuItem::Folder(
fl!("indentation"),
vec![
MenuItem::CheckBox(
fl!("automatic-indentation"),
config.auto_indent,
Action::ToggleAutoIndent,
),
],
),
```
- Added `Checkbox` and `Folder` variants to `MenuItem`.
- Exported `menu_button` macro.
- Renamed `MenuItem::Action` to `MenuItem::Button`
> improv(menu): add more menu item types.

- Cargo.toml
- cosmic-config/Cargo.toml
- cosmic-theme/Cargo.toml
- cosmic-theme/src/output/gtk4_output.rs
- cosmic-theme/src/output/mod.rs
- src/config/toolkit.rs
This is still a bit incomplete, and some apps use their own custom variables as well, for example the gtk4 text editor. It does work well as far as I can tell, aside from when the gtk4 text editor uses a dark theme and the css is a light theme. This is because it uses custom variables. As it is, this won't actually write to gtk.css, so to test, you have to copy the file to gtk.css.
> chore: update gtk4-output for the theme to set adwaita named colors

- examples/cosmic/src/window/demo.rs
- src/icon_theme.rs
- src/widget/icon/named.rs
This will fallback to the Cosmic icon theme when an icon isn't found in the default. It does clash a bit with the existing fallback strategy, and I'm not sure if we would prefer to give that priority?
> fix: fallback to Cosmic icon theme

- src/applet/mod.rs
`StatusNotifierItem` can use either named icons, or pixmap data. So to support the latter, it needs a way to show a non-named icon with the same button styling as any other planel applet icon.
The `StatusNotifierItem` protocol actually supports sending different icons with different sizes, so ideally we'd want a `icon::Data` variant that contains multiple sizes? But just using the largest and scaling works for now.
> applet: Add `icon_button_from_handle`

- examples/text-input/Cargo.toml
- examples/text-input/src/main.rs
- src/theme/style/text_input.rs
- src/widget/text_input/input.rs
This widget renders as if it were a normal text widget, but becomes a variation of an inline text input when toggling the edit mode.
> Add `editable_input` widget

- src/widget/segmented_button/widget.rs
Fixes alignment of segmented controls which use center-aligned buttons without text. Previously, it was assumed that there would be text, and some additional button spacing would be added to the button width calculation.
> fix(segmented-button): misaligned icon when text is empty

- src/widget/text_input/input.rs
The text in the inputs of the context drawer in cosmic-tasks exceed the boundaries of the text input initially until redrawn. The measurement of the text width may be incorrect when the widget is first initialized, but the layer clipping logic solves the issue either way.
> fix(text_input): clip text in text_input if they exceed initial bounds

- cosmic-config/src/lib.rs
This allows creating a cosmic config at a custom path, which might be useful for some applications.
> feat: custom config path

- src/widget/text_input/input.rs
- Emits the `on_toggle_edit` message when the widget loses focus
- Allows entering edit mode by clicking on the text.
> Editable input widget improvements

- .vscode/settings.json
I added this a while back because my libcosmic tooling wasn't working. Now it seems to work the other way, removing this line caused my tooling to work again.
> fix: remove rust-analyzer.linkedProjects

- examples/cosmic/src/window.rs
- examples/nav-context/Cargo.toml
- examples/nav-context/src/main.rs
- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/widget/menu.rs
- src/widget/menu/menu_bar.rs
- src/widget/menu/menu_inner.rs
- src/widget/menu/menu_tree.rs
- src/widget/nav_bar.rs
- src/widget/segmented_button/widget.rs
Adds context menu functionality to the segmented button widget and its variations.
Utilizes the menu tree API that the menu bar widget is using.
> feat!(segmented_button): Add context menu support and integrations

- examples/context-menu/Cargo.toml
- examples/context-menu/src/main.rs
- examples/nav-context/src/main.rs
- src/app/mod.rs
- src/widget/context_menu.rs
- src/widget/menu.rs
- src/widget/mod.rs
- src/widget/nav_bar.rs
- src/widget/segmented_button/widget.rs
This provides a popover-style widget which displays a context menu using the menu tree API. Which will enable creating a popover over any widget that is embedded into it. This also applies ergonomic improvements to the imports of the menu widget types and functions.
> feat(context_menu): add context menu widget as menu tree alternative to the popover widget

- cosmic-theme/src/steps.rs
> Requires update to cosmic-settings to use the new values when generating a theme.
Currently, light themes are getting darker surfaces when the background lightness is below 89. In Figma, themes with background lightness above 88 have their surfaces darkened; whereas below 88 have their surfaces lightened. This fixes custom light theme surfaces being unusually dark against a darker background. Some comparisons below using color schemes from Figma
Figma
Before
After
> fix(theme): light theme surface lightness is inverted

- cosmic-theme/src/model/derivation.rs
- cosmic-theme/src/model/theme.rs
- cosmic-theme/src/steps.rs
- src/theme/style/button.rs
- src/theme/style/iced.rs
- src/theme/style/segmented_button.rs
This improves our theming by a decent margin
- Fixes background layer hover styling on the light theme
- Text color is now based on the lightness value of the container
- Buttons, SegmentedButtons, and the NavBar now inherit the text color as well
- Fixed styling of active buttons in segmented button controls
- The `@small_container_widget` variable is directly affected by container layers, so it's been promoted as a property of the `Container` struct. This is given a 0.25 alpha to match the Figma designs.
These are the main issues remaining
- Accent color has poor contrast when the container background is dark while the application background is light; and vice versa
- Neutral palette colors are reversed when the container background is dark while the application background is light; and …
> improv(theme): theme generation improvements

- cosmic-theme/src/model/theme.rs
Hi
Today tried libcosmic on Pop_OS with current Gnome implementation. The problem was with preferred color palette in libcosmic apps. I'm using light theme in my OS and apps was started always as dark theme. Before I was added these feature to my app when using Iced and it was working so considered to add this to libcosmic. I'm not sure if you want to see such features. The implementation is very simple based on `gsettings` app and `color-scheme` value. From my tests on pop os it's working. It should work everywhere where gsettings are installed, otherwise it will default to dark theme as before so nothing lost here :) Would be nice to see it implemented.
> [feat] set default color palette based on user preference

- src/theme/style/button.rs
- src/theme/style/iced.rs
- src/theme/style/text_input.rs
- src/widget/context_drawer/widget.rs
- src/widget/text_input/input.rs
- src/widget/text_input/style.rs
> Fix icons and text in header bar not inheriting accent color from header bar container style

- src/applet/mod.rs
This will allow applets to know whether they are on a Panel, Dock, or other named panel.
> feat(applet): add panel type attribute to applet context

- src/app/mod.rs
May fix desktops with integrated graphics having a delay on startup.
> fix: avoid setting WGPU_POWER_PREF=low if system is desktop

- src/app/mod.rs
- src/theme/style/button.rs
- src/widget/nav_bar_toggle.rs
I don't think the alpha is actually working for the icon, but the color should match.
> feat: update the headerbar to match figma

- src/theme/style/iced.rs
- src/widget/context_drawer/widget.rs
the `layer` method needs to be called before the `style` method as it also sets the style of the container.
> fix: context-drawer border & radius

- src/app/core.rs
- src/applet/mod.rs
- src/theme/style/button.rs
- src/theme/style/iced.rs
- src/widget/button/link.rs
- src/widget/button/mod.rs
- src/widget/button/text.rs
- src/widget/button/widget.rs
- src/widget/calendar.rs
- src/widget/color_picker/mod.rs
- src/widget/header_bar.rs
- src/widget/menu/menu_tree.rs
This also requires specializing our button widget so it is now a `Button<'a, Message>` instead of `Button<'a, Message, crate::Theme, crate::Renderer>`.
> Fix header bar buttons not inheriting icon and text color from headerbar container

- src/widget/text_input/input.rs
@mmstick is there a reason why only an editable text input should forward events to the trailing icon? If not, this should fix the trailing icon buttons.
> Fix text input trailing icon

- src/widget/text_input/input.rs
This fixes an attempt to subtract with overflow by checking if `children.len() > 0` beforehand.
I'm unsure if this is what we're looking for in this part of the code, @wash2 can you double check this please?
See the [log](https://github.com/pop-os/libcosmic/files/15384768/libcosmic.log) for more details.
> fix: text input attempting to subtract with overflow

- cosmic-theme/src/output/gtk4_output.rs
_(This covers colors, hover background color, window active/inactive state colors, transitions (animations) and more...)_ 
**Examples below ( ↓ )**
**Eddy - GTK3 (Light/Dark)**
**Flatseal - GTK4|libadwaita (Light/Dark)**
**Main Menu - GTK4|libadwaita (Light/Dark)**
**Nautilus (GNOME Files) - GTK3 (Light/Dark)**
> Theme GTK3/4 window controls to match COSMIC theme

- src/widget/flex_row/layout.rs
- src/widget/flex_row/widget.rs
- src/widget/grid/layout.rs
- src/widget/grid/widget.rs
- src/widget/icon/mod.rs
- src/widget/menu/menu_tree.rs
- src/widget/mod.rs
- src/widget/settings/item.rs
- src/widget/settings/mod.rs
Fixed alignment of menu buttons, and uses icons instead of unicode text
Improvements for the Grid widget:
- Fixes padding not being applied correctly
- Fixes widget using incorrect width and height for its layout
- It's now possible to add it to a container and center with `container.center_x()`
- Adds `justify_content` property
- Sets `flex_grow` when a widget is `Fill`
Improvements for the FlexRow widget:
- Rewrites layout with taffy, as used by the grid widget
- Adds `align_items`, `justify_items`, and `justify_content` properties
- Adds `min_item_width` property for wrapping text widgets set to Fill
Adds `flex_` variants of `settings::item`, `settings::item_row`, and `settings::Item::control`
Other improvements
- Added re-exports for the Canvas and TextEdit widgets from Iced
- Removed …
> Various widget improvements

- src/app/cosmic.rs
the user may have set a preferred value which should be used.
> fix: use the user provided theme even when setting system theme

- Cargo.toml
- src/widget/text_input/input.rs
- text input implements widget id methods
- text input can be set to always_active now, which is useful in the launcher
- update iced with fixes for macos
- expose clipboard feature
> small fixes

- src/widget/segmented_button/widget.rs
Only close on middle button release if the middle button press event was on the same tab.
This changes was needed for: https://github.com/pop-os/cosmic-files/pull/266
> Fix for closing tab with middle-click

- src/widget/nav_bar.rs
- src/widget/segmented_button/widget.rs
This is required to implement middle-click to open in a new tab from nav bar in COSMIC Files.
Relevant issue: https://github.com/pop-os/cosmic-files/issues/261
Will be implemented in: https://github.com/pop-os/cosmic-files/pull/266
> Add on_middle_press to nav bar and segmented button

- src/widget/mod.rs
- src/widget/toaster/mod.rs
- src/widget/toaster/widget.rs
Attempt to implement https://github.com/pop-os/cosmic-files/issues/183
I implemented this feature in fan-control. You can see the change i needed to make in [this commit](https://github.com/wiiznokes/fan-control/compare/master...toats).
The duration chosen comes from [Android](https://stackoverflow.com/questions/7965135/what-is-the-duration-of-a-toast-length-long-and-length-short).
There is more just to match the Ui design, but the idea is there. I'm not sure i will implement it as i don't really know where to search for padding, colours, ect..
> feat: toast widget

- src/widget/toaster/mod.rs
Weird, i can't compile fan-control without this change
> fix: change message bound for toaster

- src/app/cosmic.rs
Requires https://github.com/pop-os/iced/pull/159/
> fix: window menus now supported by windows using wayland feature

- cosmic-theme/src/output/mod.rs
- cosmic-theme/src/output/vs_code.rs
> fix: return error if vscode config fails to parse, instead of overwriting

- .github/workflows/ci.yml
- Cargo.toml
- src/desktop.rs
- src/process.rs
This is needed for things like `xdg-desktop-portal` to get the app ID from a pid, in unsandboxed apps.
A couple things still should be fixed here, then `cosmic-launcher`, `cosmic-app-list`, and `cosmic-app-library` will need to be updated to use this.
> Call systemd `StartTransientUnit` when starting app

- src/app/cosmic.rs
- src/app/mod.rs
- src/applet/mod.rs
- src/config/mod.rs
- src/icon_theme.rs
- src/theme/mod.rs
- src/widget/button/icon.rs
- src/widget/button/style.rs
- src/widget/button/text.rs
- src/widget/button/widget.rs
- src/widget/calendar.rs
- src/widget/color_picker/mod.rs
- src/widget/dialog.rs
- src/widget/icon/named.rs
- src/widget/segmented_button/widget.rs
- src/widget/text_input/input.rs
Better support for multi-threaded applications, especially cosmic-comp rendering in parallel on multiple threads, each potentially accessing global configurations such as the active theme, icon_theme and more...
This is already causing issues like https://github.com/pop-os/cosmic-comp/issues/671
Note: Leaves the SUBSURFACE-thread-local untouched. It is not part of the public api and looking at it, I am not sure it is possible to have access to this from multiple threads. cosmic-comp also has no business with iced-sctk, so this a non-issue for the cases I want to fix here. (Ping @ids1024 on this specifically.)
> fix: Use globals instead of thread-locals

- Cargo.toml
https://github.com/pop-os/libcosmic/pull/557 uses `std::sync::LazyLock`, which was only introduced in the latest stable release.
> chore: Update MSRV

- src/widget/header_bar.rs
Fix for #559 (credit to @wiiznokes for the fix).
> Set non-linux window control icons as symbolic

- src/theme/style/iced.rs
Very minor thing at this point. This makes the Toggle widget radius more pleasing by making the radii concentric. Most noticeable with the "Slightly round" style, as indicated in the application to the right, with the current look in the settings panel to the left. It is subtle, but something people will notice at least subconsciously.
> Make `Toggle` handle and border radius concentric

- src/widget/menu/menu_tree.rs
Adds a horizontal padding of 8 to the menu divider, to match designs.
> Add horizontal padding to menu divider

- src/widget/text_input/input.rs
Switch between the eye icon and the icon with a slash through it when clicking on it.
For #422 the visibility toggle was already working, but the icon didn't change. Also the greeter wasn't using `secure_input` for its password input, so the toggle didn't work. I opened https://github.com/pop-os/cosmic-greeter/pull/89 to fix this.
> Switch icon when toggling visibility of secure input

- src/widget/mod.rs
- src/widget/toaster/mod.rs
This fixes toasts clearing immediately without the `tokio` feature enabled, and switches `Toasts` to stable slotmap ids instead of indices which fixes toast duration removing wrong toasts and end up clearing toasts too early or not at all.
Currently the queue can have "ghost keys" build up when toasts are cleared with the public api, and they remove clear themselves when the toasts amount reaches the limit. I'm not sure if this is a problem.
> Toaster Improvements

- cosmic-theme/src/model/theme.rs
Hello,
Some time ago I made PR where we could read gsettings values for preferred color scheme.
I assumed it will be `prefer-light` for light theme, but GNOME has also `default` value for light theme (basically it's "mixed" theme (?)) so we should read this value also and treat it as light theme I guess, which is a thing in Ubuntu for example.
> fix: dont omit default preference for light theme

- src/widget/mod.rs
- src/widget/radio.rs
Adds a custom radio widget, that allows for a full element rather than a single label next to the radio button.
Useful for more complex labels like:
> widget: Add custom radio widget

- src/widget/menu/key_bind.rs
This will fix https://github.com/pop-os/cosmic-files/issues/286 and https://github.com/pop-os/cosmic-term/issues/317 in a simpler way than https://github.com/pop-os/cosmic-files/pull/428
> fix(menu): Ignore Key::Character case when matching KeyBind

- .github/workflows/ci.yml
- examples/context-menu/src/main.rs
- examples/cosmic/src/window.rs
- examples/nav-context/src/main.rs
There were changes like these: 1) https://github.com/pop-os/libcosmic/commit/547423279 2) https://github.com/pop-os/libcosmic/commit/31ea71d , that have broken some of the examples since we do not test all of them in CI here: https://github.com/pop-os/libcosmic/blob/master/.github/workflows/ci.yml#L79-L81
I was looking at the repo and just found them, i think there might be more.
e.g. :
> (chore) Various broken examples fixes.

- src/widget/list/column.rs
This ensures that the vertical space between the top/bottom list items and the edges of the container remains the same as the spacing between items, when the `list_column` spacing is changed from default.
Needed to match the spacing from the designs for list columns on some Settings pages.
Another issue is that dividers (e.g. `divider::horizontal::light()`) seem to have around 2 px of vertical padding (which `horizontal_rule` doesn't have), which makes things at the ends of a list off-center, but I haven't been able to find where that padding comes from.
Not sure if the padding should be removed, or `horizontal_rule` used in places where that padding isn't desirable.
> [list_column] Match container padding to list spacing

- .gitmodules
- Cargo.toml
- examples/README.md
The design-demo example was removed in the commit f0bfa87. The submodule was then added back by @wash2 in the commit f9af93c. The commit was about was about updating iced so I suspect it got added back by accident.
In issue #374 @mmstick said about it: "The project is not maintained right now. It should be removed."
I have removed the design-demo example again along with some other leftover parts. I also fixed the examples README.md file.
This closes issue #374
> Remove design-demo example again

- src/widget/menu/menu_tree.rs
Uses the accent color for the checkmark, to match designs.
> Use accent color for menu checkbox

- examples/README.md
The documentation was missing for some of the examples. This adds documentation for the other examples, except `cosmic` which is deprecated and currently not compiling.
> Document examples

- src/app/core.rs
- src/app/cosmic.rs
- src/app/mod.rs
This is in order to support https://github.com/pop-os/cosmic-files/issues/109. There are some small hacks but it is a relatively small change and functional.
> feat(app): allow context drawer to be laid out next to content

- cosmic-theme/src/model/density.rs
- res/icons/navbar-closed-symbolic.svg
- res/icons/navbar-open-symbolic.svg
- src/app/core.rs
- src/app/mod.rs
- src/widget/header_bar.rs
- src/widget/nav_bar_toggle.rs
- src/widget/text_input/input.rs
Increases Compact header height to 40 (from 36), to better accommodate larger widgets (e.g. the search bar). This makes it distinct from the SSD header, which is now addressed by the `_` match case.
This needs a change in cosmic-comp at [this line](https://github.com/pop-os/cosmic-comp/blob/afdb65677857946b403043f04ca083810639e4e5/src/shell/element/window.rs#L506), in order to keep the current SSD style when libcosmic is updated there.
Also makes the horizontal header padding fixed at 8, so that the app window padding can also be 8.
Fixes #620.
Fixes #619.
(also https://github.com/pop-os/cosmic-epoch/issues/523 can probably be closed, since the Compact header exists).
Feel free to suggest improvements to the Density documentation wording (just added it to remove a warning).
> Compact density padding fixes

- cosmic-theme/src/model/theme.rs
This makes the `small_widget_divider` color match the designs, and thus fixes the divider color in the horizontal `segmented_button`. Also tweaks the values of `neutral_9` to match the designs (the diff is a bit hard to see).
The background color of the horizontal segmented button doesn't match designs, but I haven't been able to figure out where the color of the `small_widget` is set.
It can mostly match if doing something like the following, but it should use the `small_widget` color:
```
SegmentedButton::Control => {
let cosmic = self.cosmic();
let mut color = cosmic.palette.neutral_7;
color.alpha = 0.1;
let active = horizontal::selection_active(cosmic, &container.component);
let rad_m = cosmic.corner_radii.radius_m;
let rad_0 = cosmic.corner_radii.radius_0;
Appearance {
background: …
```
> Fix color of horizontal segmented button divider

- Cargo.toml
- src/desktop.rs
With this change, anything wanting to launch desktop files in systemd scopes must use the desktop-systemd-scope feature. I'm open to alternatives, my primary use case for this is avoiding a zbus dependency when enabling the desktop feature
> Make use of systemd scopes optional

- examples/application/src/main.rs
- examples/calendar/src/main.rs
- examples/context-menu/src/main.rs
- examples/cosmic/src/window.rs
- examples/image-button/src/main.rs
- examples/nav-context/src/main.rs
- examples/open-dialog/src/main.rs
- examples/text-input/src/main.rs
- src/app/mod.rs
- src/applet/mod.rs
- src/widget/aspect_ratio.rs
- src/widget/calendar.rs
- src/widget/color_picker/mod.rs
- src/widget/context_drawer/widget.rs
- src/widget/header_bar.rs
- src/widget/layer_container.rs
- src/widget/list/column.rs
- src/widget/menu/menu_tree.rs
- src/widget/nav_bar.rs
- src/widget/rectangle_tracker/mod.rs
- src/widget/scrollable.rs
- src/widget/settings/item.rs
- src/widget/settings/mod.rs
- src/widget/spin_button/mod.rs
- src/widget/warning.rs
This adds a border around windows, and removes the 8px padding around the content, allowing the scrollbar to go to the edge (to match designs).
Also adds some invisible padding around non-maximized windows, so that the `resize_border` is more outside the window, to not interfere with the scrollbar.
This significantly improves the floating window resize UX, but currently also adds padding around tiled windows, so it should maybe be removed until there's a way to differently handle tiled windows (might already exist, but I haven't been able to find it), or if it's planned to do it in a better way than adding invisible padding (so that resize indicators don't show up when the cursor is at the edges of maximized windows, as they do now).
I tried to also add a window shadow, but it looked …
> Add window border

- src/app/mod.rs
I noticed that the cosmic-term terminal box was bounded by invisible padding when updating libcosmic, so this ensures that apps that set `content_container` to false display properly.
This change is of course temporary, as is the padding around main_content.
> Apply content padding only when content_container is true

- src/app/mod.rs
Removes spacing between the footer and content, until the `resize_border` is moved.
> Remove extra spacing for footer

- src/app/mod.rs
- src/widget/context_drawer/widget.rs
This fixes the cosmic-term terminal_box becoming cropped when opening a context drawer.
Also fixes the misalignment for main content caused by #687 and makes the context drawers use spacing variables.
> Fix app padding

- Cargo.toml
- src/theme/style/iced.rs
- src/widget/mod.rs
The `Catalog` implementation was copied from Iced (the `Catalog` api is a nightmare to understand)
Here is a screenshot of fan-control showcasing this feature
> feat: export markdown iced feature

- Cargo.toml
- examples/about/Cargo.toml
- examples/about/src/main.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/widget/about.rs
- src/widget/mod.rs
Per @wiiznokes suggestion in #696, the About section code was moved to a widget.
Closes #696
> Move About to a widget

- src/app/mod.rs
- src/widget/context_drawer/mod.rs
- src/widget/context_drawer/widget.rs
This adds configurable actions to the left side of the context drawer header. Not sure if it would be better to make the title optional, since it needs to be wrapped in `text::heading()`, so it would need a similar check regardless.
Maybe fixes #625.
Not quite sure why the scrollable for context drawer content was removed, since even those with only 1 item have to have a scrollbar at minimum vertical size. Every app will now have to also add `.padding([0, space_l, space_l, space_l])` to the content being added to a context drawer for each context drawer, in order for the scrollbar (if present) to be next to the edge of the drawer.
The second commit removes the built-in padding.
> [Context Drawer] Add actions to header

- src/app/mod.rs
- src/widget/about.rs
- src/widget/context_drawer/mod.rs
- src/widget/context_drawer/widget.rs
This adds an optional element placed below the title row, so that the rest of the content can be wrapped in a scrollable.
Example of the current (likely suboptimal) API:
```
fn context_header_opt(&self) -> Option<Element<message::Message<Self::Message>>> {
match self.context_page {
ContextPage::NetworkDrive => Some(
widget::column::with_capacity(2)
.spacing(space_m)
.push(widget::text_input(
fl!("enter-server-address"),
&self.network_drive_input,
))
.push(widget::text(fl!("network-drive-description")))
.into(),
),
_ => None,
}
}
```
Draft until a possibly better API is devised, if feasible.
> [Context drawer] Add optional header and footer element

- src/widget/list/column.rs
Fixes sliders and flex row widgets in cosmic-settings
Reference https://github.com/pop-os/cosmic-settings/pull/764
> fix(list_column): broken sliders and flex row in cosmic-settings

- Cargo.toml
- src/widget/about.rs
- src/widget/mod.rs
#697 added the license dependency, which requires `error_in_core`, which was only added in rust 1.82 released less than a month ago. Libcosmic targets a minimum rust version of 1.80. This PR makes a new about feature that brings in the license dependency, rather than having it part of the desktop feature.
> Move about widget to new about feature

- Cargo.toml
- src/widget/aspect_ratio.rs
- src/widget/autosize.rs
- src/widget/context_drawer/widget.rs
- src/widget/context_menu.rs
- src/widget/dnd_destination.rs
- src/widget/dnd_source.rs
- src/widget/dropdown/widget.rs
- src/widget/header_bar.rs
- src/widget/id_container.rs
- src/widget/layer_container.rs
- src/widget/popover.rs
- src/widget/rectangle_tracker/mod.rs
This adds implementations to most libcosmic widgets missing them, and includes an iced fix that should allow libcosmic apps to produce a proper accessibility tree again.
> feat: better a11y support

- src/app/cosmic.rs
- src/app/mod.rs
- src/app/settings.rs
The app can request to be treated by iced as a daemon so it can perform cleanup when its main window is closed.
This is necessary for the settings app at the moment.
> refactor: add is_daemon setting

- examples/about/Cargo.toml
- examples/about/src/main.rs
- src/app/context_drawer.rs
- src/app/core.rs
- src/app/mod.rs
- src/widget/context_drawer/mod.rs
- src/widget/context_drawer/widget.rs
- src/widget/mod.rs
This pr implement the design from this comment https://github.com/pop-os/libcosmic/pull/699#issuecomment-2466828302.
It seems to works as expected, but i think it will cause problem, because in this design, the field `core.windows.show_context` is not meant to be changed. It is used in some calculation for responsiveness if i understand correctly.
Notably:
```rs
/// Call this whenever the scaling factor or window width has changed.
#[allow(clippy::cast_precision_loss)]
fn is_condensed_update(&mut self) {
// Nav bar (280px) + padding (8px) + content (360px)
let mut breakpoint = 280.0 + 8.0 + 360.0;
//TODO: the app may return None from the context_drawer function even if show_context is true
if self.window.show_context && !self.window.context_is_overlay {
// Context drawer min width (344px) …
```
> feat: ContextDrawer struct in Application trait

- src/theme/style/iced.rs
- src/widget/context_drawer/widget.rs
This makes the primary container style use `radius_s`, instead of `radius_xs`, which matches the radius of the footer to the designs.
Also fixes the vertical padding of the `context_drawer` footer.
Since other container styles also used `radius_xs`, I also changed them for consistency.
Testing with `cosmic-files`, I didn't notice anything unusual from this change, but not sure if this should be done, or if the footer should use a custom style (though there isn't a `Custom` Layer enum).
> Fix footer corner radius

- src/app/mod.rs
It seems that the reason behind issue #700 is that when iced_settings is being called in app::run, in the multi-window version it sets the main_window flag in the iced settings but it wasn't doing that in the standard version
> Fixed issue #700 where multi-window was required for window header to be interactable

- examples/about/src/main.rs
- examples/application/src/main.rs
- examples/calendar/src/main.rs
- examples/context-menu/src/main.rs
- examples/image-button/src/main.rs
- examples/menu/src/main.rs
- examples/nav-context/src/main.rs
- examples/open-dialog/src/main.rs
- examples/text-input/src/main.rs
- src/app/command.rs
- src/app/mod.rs
- src/dialog/file_chooser/mod.rs
- src/lib.rs
- src/task/mod.rs
- src/widget/toaster/mod.rs
This changes the cosmic::command module to cosmic::task ever since the change from Command to Task, and also fixes an inconsistency where cosmic::Task was a re-export of iced::Task while cosmic::app::Task was a different type alias
> Changed cosmic::command to cosmic::task, and made cosmic::Task consistent with cosmic::app::Task

- src/app/mod.rs
- src/theme/style/iced.rs
- src/widget/header_bar.rs
This removes the background of the header bar and content containers, and moves it to the container wrapping both, in order for the border to be drawn properly.
The second commit matches the spacing of buttons in header bar sections to the designs.
Edit: Apps without content containers but with a header bar won't benefit as much (they do see a slight improvement), but not sure if it's possible to do something about that.
A thing that would enable fixing this (and would be useful for other things), is for the border/border color to be settable per-side, which would enable setting the border in the individual containers, rather than in the wrapping container in `app/mod.rs`, which could then likely be removed (though not sure about the drawing logic in the corners).
An API for that could be …
> Fix window border corner appearance

- src/app/mod.rs
- src/theme/style/iced.rs
This undoes the style changes in #732, since they aren't necessary, and makes stuff less messy and less of a breaking change in some cases (like `cosmic-files-applet` windows).
The added background for the app container is enough to make the borders look good.
Not sure what to call the commit, so I just called it `fix`.
> Partially undo #732

- src/widget/segmented_button/model/mod.rs
When trying to set position greater then length of the Deque, the method fallbacks to position equal to the Deque length. However, that value changes immediately after getting this fallbacked position with removal of the item (to prepare it for re-instert) and as a result the code panics with index out of bounds error.
Reordering of the code fixes this issue.
> Fix segmented button model index out of bounds when setting position

- Cargo.toml
Switch to a fork that we maintain, which contains a few fixes that haven't been merged upstream yet.
https://github.com/pop-os/freedesktop-icons/commits/main/
> fix: switch to cosmic fork of freedesktop-icons

- src/app/mod.rs
- src/theme/style/button.rs
- src/theme/style/iced.rs
- src/widget/dropdown/menu/mod.rs
- src/widget/dropdown/multi/menu.rs
- src/widget/header_bar.rs
- src/widget/nav_bar_toggle.rs
This makes the NavBar toggle use `radius_s` for the button radius, to match designs. Adding a new enum value just for that feels a bit messy, but using Button::Custom feels potentially messier (and I'm not entirely sure how to do it). This could be removed if it's decided to use `radius_s` for all header bar buttons in the future.
~~Introduces a `horizontal_padding` field to the header bar, which is needed for the padding offset, but can also be used by `cosmic-comp` to make window controls more centered in the SSD corners. Though this can be removed if it'll be eventually possible to set the borders on individual container sides, which would remove the need for the offset, and if SSDs should have the same horizontal padding of 8 as apps.~~ I removed this, since it caused the header …
> Use `radius_s` for NavBar toggle

- src/desktop.rs
- src/lib.rs
This pull request includes changes to improve cross-platform compatibility by conditionally compiling code for non-Windows platforms and adjusting feature flags. The most important changes include adding conditional compilation attributes to various functions and structs in `src/desktop.rs`, and modifying the feature flag conditions in `src/lib.rs`.
* `src/desktop.rs`: Added `#[cfg(not(windows))]` attributes to several `use` statements, functions, and structs to ensure they are only compiled on non-Windows platforms.
* `src/lib.rs`: Modified the `process` module to only be included when both the `process` feature is enabled and the target platform is not Windows.
> fix: improve cross-platform compatibility 

- src/widget/menu/menu_inner.rs
- src/widget/segmented_button/widget.rs
Fixes navbar context menu issue in Cosmic Files:
https://github.com/pop-os/cosmic-files/issues/381
It also makes it so clicking out of a menu with right and middle mouse buttons closes the context menu, just like left-clicking does.
> Fixes for context menu for segmented button

- src/widget/text_input/input.rs
Previously entering text in text inputs with the compose key would insert one or more NUL bytes before the inserted character.
Fixes an issue in Cosmic Files when creating or renaming files and the Compose key is used to enter special characters.
https://github.com/pop-os/cosmic-files/issues/681
> Fix entering text with compose key

- src/widget/dnd_source.rs
- src/widget/text_input/input.rs
The `drag_icon` callback is passed the offset of the cursor within the widget at the start of the drag, and can return an offset the drag surface should be placed relative to the cursor.
Requires https://github.com/pop-os/iced/pull/206.
> dnd_source: Add suppport for surface offset

- Cargo.toml
rfd enables the 'async-std' feature by default, which causes a compile error when the 'tokio' feature is also enabled. This PR changes the libcosmic dependencies so that rfd only has 'xdg-portal' enabled by default (rfd only imports ashpd conditionally based on compile target, so this feature should be fine to leave always enabled) and enables the 'async-std' feature of rfd if the libcosmic 'smol' feature is enabled.
> fix: Don't enable rfd/async-std by default

- src/widget/text_input/input.rs
This is useful to be able to translate the label directly in the `view` function, instead of having to store a translation in the app state.
> TextInput: use Cow instead of reference for label, helper text and error text

- examples/calendar/src/main.rs
- src/widget/calendar.rs
This PR fixes #632 getting the calendar more in line with what is the standard for calendar widgets. Its now showing (currently showing) month and year at the top and selected day is in the grid if the selected day is in current visible month. Like in the jquery example from the issue mentioned above. 
-  plus some QoL methods for the CalendarModel
-  plus updated calendar example
Even-though this widget would deserve having some internal model, I did not change that 'yet' to keep it more in line with how it already worked.
> next/previous months should not select the date #632 

- src/widget/calendar.rs
This pull request adds several standard derived traits to the `CalendarModel` struct to allow more flexibility.
> Add standard derive attributes to CalendarModel

- src/widget/calendar.rs
I made the field 'visible' of the model public (like the 'selected' field) because we might want to use it to directly affect what the calendar shows. Added another QoL method to the model. (original PR #789)
> CalendarModel make visible prop public, add convenience method

- src/widget/icon/mod.rs
This PR exposes a field `rotation` to COSMIC icons to allow you to, well, rotate an icon.
This feature already exists in `iced_core`, for both image and SVG icons, so we're simply exposing the field.
example:
```rust
use cosmic::widget::{self, settings, icon};
use std::f32::consts::PI;
use cosmic::iced_core::Rotation;
widget::column::column()
.push(
settings::section()
.add(settings::item("no rot", icon::from_name("folder-download-symbolic").size(32).icon()))
.add(settings::item("0 deg | (0pi) rad", icon::from_name("folder-download-symbolic").size(32).icon().rotation(Rotation::from(0.0))))
.add(settings::item("90 deg | (pi / 2) rad", icon::from_name("folder-download-symbolic").size(32).icon().rotation(Rotation::from(PI / 2.0))))
.add(settings::item("180 deg | (pi) rad", …
```
> Add rotation field into COSMIC icon

- cosmic-config/Cargo.toml
- cosmic-theme/Cargo.toml
- examples/config/Cargo.toml
Ron 0.9 has been in the works for years at this point (0.8 the latest stable was tagged in August 2023), but sadly has stalled quite a bit: https://github.com/ron-rs/ron/issues/496
It adds a bunch of really nice features, like support for tagged or untagged enum variants, but more importantly it has a new `RawValue` type (similar to `serde_json::RawValue`), which allows us to address a few shortcomings like: https://github.com/pop-os/cosmic-settings-daemon/pull/68
I say, lets bite the bullet and try the alpha-version of it. It seems remaining issues are only around `#[serde(flatten)`, which we don't use: https://github.com/search?q=org%3Apop-os%20%23%5Bserde(flatten)%5D&type=code
> chore: Update ron to 0.9

- cosmic-theme/src/model/theme.rs
- cosmic-theme/src/steps.rs
> Fix accent text

- src/keyboard_nav.rs
fixes https://github.com/pop-os/libcosmic/issues/787
> fix: filter out tab events with control modifier

- README.md
If you just blindly copy and paste from the README, you get errors. That's annoying. Better if it just works.
```
tyler@HOST:~/libcosmic$ just check
cargo clippy --no-deps --features="wayland,tokio,xdg-portal"  -- -W clippy::all -W clippy::pedantic
Updating crates.io index
Updating git repository `https://github.com/jackpot51/rust-atomicwrites`
Updating git repository `https://github.com/pop-os/dbus-settings-bindings`
error: failed to get `iced` as a dependency of package `cosmic-config v0.1.0 (/home/tyler/libcosmic/cosmic-config)`
Caused by:
failed to load source for dependency `iced`
Caused by:
Unable to update /home/tyler/libcosmic/iced
Caused by:
failed to read `/home/tyler/libcosmic/iced/Cargo.toml`
Caused by:
No such file or directory (os error 2)
error: Recipe `check-wayland` …
```
> fixup README

- src/widget/segmented_button/widget.rs
this fixes an interesting bit of behaviour in `cosmic-edit` where , if you try to select some text and end up highlighting an entry in the project view, you end up opening the entry (rather than ignoring / eating the event, which is standard across other similar products)
https://github.com/user-attachments/assets/66501781-f0ba-4194-8e5b-6bb4214ef09e
as an aside, this code can also be used as the basis to add a new `on_move(a, b)` event, which could be used to easily move files in `cosmic-edit` or rearrange your favourites in `cosmic-files` (i'm happy to implement this, just don't want to step on any toes!)
this should also fix a similar bit of interesting behaviour where, if the file selector extension dropdown overlaps an entry in the nav, and you select a dropdown entry, it process …
> Ignore ButtonRelease / FingerLifted events on nav model when dragged out of target

- src/app/mod.rs
- src/theme/style/iced.rs
This makes the window corners have a radius of 1/2 padding (4) larger than the content (context drawer, navbar), for values of `@radius_s` of 4 or more.
Also sets the progress bar radius to `@radius_xl` to match designs.
Closes #767.
> Visually align window corners to content

- src/widget/popover.rs
- src/widget/table/mod.rs
- src/widget/table/model/entity.rs
- src/widget/table/model/selection.rs
- src/widget/table/widget/compact.rs
- src/widget/table/widget/standard.rs
- src/widget/text_input/input.rs
- Removed local `State` because its only `is_over` property was never actually correct
- A popover is always considered to be open whenever a popup element is attached.
- Modal popovers now correctly block clicks outside of the popup overlay while open
> fix(popover): modal popover handling broken

- examples/spin-button/src/main.rs
- src/widget/about.rs
- src/widget/context_drawer/widget.rs
- src/widget/header_bar.rs
- src/widget/list/column.rs
- src/widget/menu/menu_tree.rs
- src/widget/mod.rs
- src/widget/segmented_control.rs
- src/widget/settings/item.rs
- src/widget/settings/mod.rs
- src/widget/tab_bar.rs
- src/widget/table/widget/compact.rs
- src/widget/table/widget/standard.rs
Matches the spacing of About widget sections to the spacing of sections elsewhere, and makes the buttons use the `Button::Link` class, since the highlight can't look good until there's a widget (or an addition to e.g. list_column) that can have the buttons take the entire size of a row (so that the highlight covers the entire row).
> Match About widget section spacing to designs

- src/app/mod.rs
Follow up to #840, this removes the padding of the overlay context drawer when content_container is false, to prevent visual issues in cosmic-term.
I removed that section of code, and later returned it, forgetting about the content container (sorry!).
> Remove context drawer padding without content container

- src/widget/about.rs
Use fde::IconSource following commit 9b9600a5d6f7a96b8293a205cabda05c0c1f1a76 for the About widget.
Fix #839
> fix(about): use fde::IconSource following commit 9b9600a5d6f7a96b8293a205cabda05c0c1f1a76

- src/widget/table/model/mod.rs
While quickly reading at table widget, I figured the sort function was suboptimal.
This PR should speed it up.
- If the sort is already done, noop
- If the sort is on the same category but with a different direction, just reverse the order
- **I believe this is something that happens a lot**
- If not, use `make_contiguous` to avoid reallocating new entities
> Improve table sort

- src/task.rs
`Task::none` is a popular variant so I think it's sensible to add it here for ease of access.
> feat: `none` task utils

- Cargo.toml
This enables the "highlighter" feature in Iced, which is used for syntax highlighting in certain widgets.
> Add "highlighter" feature

- src/widget/calendar.rs
- src/widget/header_bar.rs
- src/widget/spin_button.rs
- src/widget/warning.rs
This mostly addresses #852, but end elements can still get pushed out at narrow widths if the center is populated (or the center is empty but there are a lot of them or some of them take a lot of space).
A proper fix would likely need some upstream improvements to the row widget to prevent children from going out of bounds (if they haven't already been made), or some kind of custom widget that would handle things as it should (so that #854 could also be fixed).
Edit: Also adds an `is_ssd` field to the bar, for different handling of SSDs.
> [Header Bar] Reduce chance of end elements being pushed out

- Cargo.toml
No longer depend on two different versions of ashpd here, and on zbus 4.x as a dependency of ashpd.
> Update `rfd` and `ashpd`

- examples/applet/src/window.rs
- src/applet/mod.rs
- src/widget/button/mod.rs
- src/widget/button/widget.rs
- src/widget/calendar.rs
- src/widget/color_picker/mod.rs
- src/widget/menu/menu_tree.rs
Buttons are often used for toggling popups, so something allowing more straightforward positioning is important.
> refactor: add optional parameter for layout offset and bounds for button handlers

- src/widget/dropdown/mod.rs
- src/widget/dropdown/widget.rs
This allows using `format!` in the `view` function rather than having to store all strings in the model
which is in theory less efficient but it's also much less likely to lead to stale data.
Closes https://github.com/pop-os/libcosmic/issues/348 and solve https://github.com/pop-os/libcosmic/issues/798
> dropdown: accept `impl Into<Cow<'_, str>`

- src/widget/dialog.rs
This pull request enhances the `Dialog` widget by adding `width`, `height`, `max_width`, and `max_height` fields to the `Dialog` struct to allow more granular control over the widget's size.
> feat: allow dialog resize

- examples/application/Cargo.toml
- examples/application/src/main.rs
- examples/calendar/src/main.rs
- examples/context-menu/Cargo.toml
- examples/context-menu/src/main.rs
- examples/menu/src/main.rs
- examples/table-view/src/main.rs
- src/surface/action.rs
- src/theme/style/menu_bar.rs
- src/widget/button/widget.rs
- src/widget/context_menu.rs
- src/widget/dropdown/widget.rs
- src/widget/menu/flex.rs
- src/widget/menu/menu_bar.rs
- src/widget/menu/menu_inner.rs
- src/widget/menu/menu_tree.rs
- src/widget/nav_bar.rs
- src/widget/responsive_menu_bar.rs
- src/widget/segmented_button/widget.rs
- src/widget/table/mod.rs
- src/widget/table/widget/compact.rs
- src/widget/table/widget/standard.rs
- src/widget/wrapper.rs
This adds menu bar popups that are enabled by default when the `wayland`, `surface-message`, and `multi-window` features are used. There are other widgets that use an overlay menu, like the context menu which could also use an update maybe after beta. I can add that now too if we would prefer though. The table widget uses context menus, and seems to position context menus strangely, and could benefit a lot from popups.
> feat: menu bar popups

- src/desktop.rs
- src/widget/header_bar.rs
Closes: #855 
The original issue mentions that several examples fail to build. They fail to build on Linux as well due to bit rot. I started fixing some of those issues until I realized that this is a larger project than I expected. :laughing: So, this PR mainly fixes the Windows build.
> fix(855): Windows build (rebased/simplified 2025-06-23)

- cosmic-config/src/lib.rs
When a transaction gets committed, the files gets written to a file in the `.atomicwrite[0-9a-Z]` folder and then gets moved to their final location. The watcher will emit two events:
- Modify(Name(To))
- Modify(Name(Both)
The last one will include both the source and the destination and is essentially a duplicate of the first event. By discarding this event, behavior seems to be the same, and all consumers of those events get only notified once instead of twice when a configuration changes.
This should avoid unnecessary computation when theme configuration changes and improve perceived performances.
Here's an example of a log where the same event is dispatched twice:
```
Key valid for dispatch: "is_dark": Event { kind: Modify(Name(To)), paths: …
```
> fix(cosmic-config): Avoid dual notifications in transaction commits

- src/app/action.rs
- src/app/cosmic.rs
- src/app/mod.rs
- src/dbus_activation.rs
This allows an application that wants to expose a DBus protocol to use the same session DBus connection, and provide a protocol on the same owned bus name.
Without this, a Cosmic app using `single-instance` that wants to provide a DBus protocol must provide it on a bus name other than `APP_ID`.
> Add `dbus_connection()` method to `app::Application` trait

- Cargo.toml
- src/widget/about.rs
The `desktop` feature depends on `xkbcommon` via `cosmic-settings-config`, which doesn't build on windows.
> fix build on windows when the `about` feature is active

- src/widget/about.rs
The icon is made to use 128px, the same size as before, and now also shrinks in case the window is too small to fit the entire icon.
Fixes #937
> Fix icon size in about widget

- src/app/cosmic.rs
- src/config/mod.rs
Like https://github.com/pop-os/cosmic-settings-daemon/pull/100. We don't appear to install default configs for these settings anywhere? And we may not want libcosmic to inherently depend on globally installed config files.
So just avoid printing errors in that case.
We may want to consider what errors `ConfigGet` returns (https://github.com/pop-os/libcosmic/pull/948) but this should do for now.
This should help with a big part of the log spam libcosmic is currently producing.
> Don't error when default config for toolkit settings is not present

- examples/about/src/main.rs
- src/widget/about.rs
This will make it possible to set custom license url if license is not at spdx.org.
I intentionally added only the commented code line in the about example so that by default it creates the spdx.org license url, but also it is clear there is other option.
> About page - allow custom license url link

- src/widget/icon/mod.rs
Updates the `Icon::size` method to correctly handle `Named` icons by using the provided size retroactively.
Should allow making the added function in https://github.com/pop-os/cosmic-notifications/pull/87 have a nicer signature, as well as making the size behavior more deterministic/consistent.
> [Icon] Use correct size variant for `Named`

- src/widget/text_input/input.rs
when we handle focus loss for the on_edit handler,, we probably want to distinguish between when we have actually lost focus, and when we haven't had it yet. This prevents an initial extra event when we create an editable input with editing as true.
> improv(input): better initial handling of focus state
