examples/cosmic/src/window.rs

I corrected a small issue with some imports for SpinButton.

Correct imports for SpinButtonModel and SpinMessage

---

src/widget/header_bar.rs
src/widget/icon.rs
src/widget/nav_button.rs

This allows an icon to be non-svg. It would fix #38

refactor: allow the icon to be non-svg

---

src/theme/mod.rs

This adds the option for a custom button theme

feat: custom button theme

---

src/widget/aspect_ratio.rs
src/widget/mod.rs

This adds a container that limits its contents to the specified aspect ratio.

feat: aspect ratio limiting container

---

examples/cosmic-sctk/src/window.rs

This adds several improvements to window handling in iced-sctk.
window drags, window resize, window toggle maximized & fullscreen, window minimization, window app id, and fixes a typo that prevented windows from notifying the application about being closed

feat: various improvements to window commands and event handling

---

Cargo.toml
examples/cosmic/Cargo.toml
examples/cosmic/src/window.rs
src/theme/mod.rs
src/widget/navigation/macros.rs

Switches from wgpu to softbuffer by default. This allows the use of cosmic-text

Softbuffer

---

Cargo.toml

This fixes the builds for cosmic-applets according to my testing https://github.com/pop-os/cosmic-applets/commit/da00e9f7c12cd97b8b45908e9f100a4fe95d597b

Fix builds for cosmic-applets

---

src/applet/mod.rs

fixes the applet feature after the last PR

fix: applet feature

---

.github/workflows/ci.yml
Cargo.toml

this includes the recent softbuffer changes, popup repositioning fix and button focusing

chore: update iced

---

examples/cosmic/Cargo.toml
examples/cosmic/src/window.rs
src/theme/mod.rs

~~Draft until https://github.com/iced-rs/iced/pull/1640 is merged upstream. Then added to our fork.~~
[tab-nav.webm](https://user-images.githubusercontent.com/58987761/210898147-390f306a-9aa6-435d-b9d1-f3387724958b.webm)

Cosmic example: Add tab navagation

---

Cargo.toml

Depends on https://github.com/pop-os/iced/pull/33.

Update iced and sctk

---

src/widget/mod.rs
src/widget/popover.rs

Needs more testing, more methods, etc. but seems to be working.

Popover container widget showing a widget in an overlay below another

---

cosmic-theme/src/model/cosmic_palette.rs
cosmic-theme/src/model/derivation.rs
cosmic-theme/src/model/theme.rs
cosmic-theme/src/util.rs
src/theme/mod.rs

This will make it easier to detect changes in the theme subscriptions

fix: derive PartialEq for Theme

---

src/widget/flex_row.rs
src/widget/mod.rs

This'll be used by the wallpaper settings page to dynamically shift wallpapers and colors to fit the width of the window. I'm sure there are other areas where a flexbox/flexcontainer-like layout is desired.

Add FlexRow widget

---

cosmic-config/src/lib.rs

APIs like inotify can provide notification for some events that don't change the contents of a file. It makes sense to ignore those here, even if the expected way to write is through the config API.
This reduces the number of events on the directory received by a single `:w` in vim from 12 to 8. And reduces a `touch` from 2 events to 1.
Atomic writes through the config API only result in 1 event per-setting, before and after this change.

config: Ignore some filesystem events

---

cosmic-theme/src/model/cosmic_palette.rs
cosmic-theme/src/model/dark.ron
cosmic-theme/src/model/derivation.rs
cosmic-theme/src/model/light.ron

changes based on https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?type=design&node-id=11616-170590&mode=design&t=w0llnCLQwO95hXtO-0

chore: update theme colors

---

Cargo.toml
src/widget/frames.rs
src/widget/mod.rs

This adds an animate image widget inspired by https://github.com/tarkah/iced_gif/

Animated image

---

examples/cosmic-sctk/Cargo.toml
examples/cosmic-sctk/src/window.rs
examples/cosmic/Cargo.toml
examples/cosmic/src/window.rs
examples/cosmic/src/window/demo.rs

This adds examples for usage of the cards widget. It is a separate PR from #129 that can be merged after https://github.com/pop-os/cosmic-time/pull/13.

Card examples

---

src/widget/list/column.rs

This PR adds custom spacing and padding to the list column widget.

Add spacing and padding to list column

---

Cargo.toml
examples/applet/Cargo.toml
examples/applet/src/main.rs
examples/applet/src/window.rs
src/app/applet/mod.rs

This PR fixes issues with the applet module.
- Code updated to use new Iced API.
- Added applet example.

Fix issues with applet module.

---

src/applet/mod.rs

This PR fixes some styling issues I missed on my last PRs.

Fix styling issues

---

Cargo.toml
cosmic-config/Cargo.toml
examples/cosmic/src/window/demo.rs
src/theme/style/iced.rs
src/widget/color_picker/mod.rs
src/widget/color_picker/style.rs
src/widget/mod.rs
src/widget/segmented_button/widget.rs
src/widget/text_input/input.rs

requires https://github.com/pop-os/iced/pull/64 or https://github.com/pop-os/iced/pull/63.
I'm looking into why the tool-tip copy buttons don't seem to be working, but otherwise I just need to fix the paths for iced and this is ready

feat: color picker

---

Cargo.toml
src/widget/grid/layout.rs
src/widget/grid/mod.rs
src/widget/grid/widget.rs
src/widget/mod.rs

Grid widget example in https://github.com/pop-os/cosmic-design-demo/pull/1
Once merged, I'll rebase the design demo to latest libcosmic changes so we can showcase it.

feat(widget): initial implementation of Grid widget

---

src/widget/grid/layout.rs

This will come with an update to the libcosmic demo to use the grid widget on the buttons page.

Grid widget fixes

---

src/dialog/file_chooser/mod.rs

Minor change to allow passing a closure to the subscription, which is less restrictive than a function.

improv(file_chooser): make subscription handler a generic closure

---

cosmic-config/src/lib.rs

Needed for greeter to pick up background changes

Add config_state_subscription for watching config states

---

src/app/mod.rs

Needed for cosmic-edit to apply custom sizing.

Allow application to customize nav bar

---

src/widget/flex_row/layout.rs

This will fix the wallpaper settings page missing its last row, and the first child of each row.

fix(flex_row): missing child nodes in layout

---

Cargo.toml
examples/application/src/main.rs
examples/cosmic/src/main.rs
examples/cosmic/src/window.rs
examples/multi-window/Cargo.toml
examples/multi-window/src/main.rs
examples/multi-window/src/window.rs
examples/open-dialog/src/main.rs
src/app/command.rs
src/app/core.rs
src/app/cosmic.rs
src/app/mod.rs
src/app/settings.rs
src/command/mod.rs
src/theme/style/iced.rs
src/widget/context_drawer/overlay.rs
src/widget/cosmic_container.rs

I still need to test this with a new example.

update to support winit multi-window

---

src/widget/dropdown/multi/widget.rs

Fixes panic when adding new options to a multi dropdown widget

fix(dropdown::multi): panic on missing paragraph

---

src/app/cosmic.rs
src/app/mod.rs

This will fix the close button doing nothing in cosmic-settings.

fix(app): closing of window in wayland

---

.github/workflows/ci.yml
justfile

- refactors the `justfile` for slightly more comprehensive linting
- a little less repetition of clippy args
- removes unmaintained github actions

refactor justfile

---

src/widget/segmented_button/widget.rs

segmented_button: mouse integrations for middle click and scrolling

---

src/widget/segmented_button/horizontal.rs
src/widget/segmented_button/widget.rs

This will fix inconsistencies in padding, alignment, and lack of hover reactivity.

fix(segmented_button): hoverable tab pagination buttons; fixed padding

---

src/app/mod.rs
src/widget/header_bar.rs

Fixes https://github.com/pop-os/cosmic-term/issues/103

Headerbar align

---

src/widget/segmented_button/horizontal.rs

This fixes a typo in the update

fix: typo in resolve for segmented button

---

src/widget/segmented_button/widget.rs

When enabled, the scroll wheel will change focus of tabs.

feat(segmented_button): add `scrollable_focus` to toggle focus scrolling

---

src/app/cosmic.rs
src/app/mod.rs

- Add Application::main_window_id to allow ids other than MAIN
- Make Cosmic and Cosmic::app public to allow custom use

Changes for multiple Application support

---

src/theme/style/iced.rs
src/widget/color_picker/mod.rs

Depends on https://github.com/pop-os/iced/pull/106
Depended by cosmic-settings

improv(slider): add styling for breakpoint and right rail

---

cosmic-theme/src/model/theme.rs
src/theme/mod.rs
src/widget/popover.rs

Cosmic Settings will also need to install the new values.

Theme shadow

---

src/app/mod.rs
src/theme/style/iced.rs
src/widget/dialog.rs
src/widget/mod.rs
src/widget/popover.rs

The Dialog widget is implemented according to the Dialog in the design system. This adds the ability to overlay a dialog on the application window contents, and there are changes to the popover widget to accomplish this.

Add support for themed application dialog

---

src/app/core.rs
src/app/cosmic.rs
src/widget/text_input/input.rs

changes needed for https://github.com/pop-os/cosmic-launcher/pull/93

Launcher changes

---

src/widget/segmented_button/horizontal.rs
src/widget/segmented_button/widget.rs
src/widget/tab_bar.rs

Segmented button layout and draw fixes

---

examples/calendar/src/main.rs
src/widget/calendar.rs

- Implemented date switching logic within the widget.
- Left a single event that provides the date after the user interacts with the calendar.

Calendar improvements

---

Cargo.toml
examples/application/src/main.rs
examples/calendar/Cargo.toml
examples/calendar/src/main.rs
src/widget/calendar.rs
src/widget/mod.rs

I'm wondering if it'd be worth it to create a model to automatically handle the date time logic.

feat(widget): add calendar widget

---

src/app/core.rs
src/app/cosmic.rs
src/app/mod.rs
src/app/settings.rs
src/config/toolkit.rs

I will be making a PR for the cosmic-settings portion soon.

feat(config): add icon theme property to CosmicTk config

---

src/widget/list/column.rs

Added the option to set a style for `list_column`.

improv(list_column): added setter for style.

---

src/widget/dnd_destination.rs
src/widget/dnd_source.rs
src/widget/mod.rs
src/widget/nav_bar.rs
src/widget/segmented_button/widget.rs

This adds dnd support for segmented buttons and the nav bar. It can be tested with https://github.com/pop-os/cosmic-files/pull/103 and it should probably not be merged until https://github.com/pop-os/iced/pull/126

Segmented button Dnd

---

src/widget/popover.rs

Fixes the popover button on the keyboard settings page in cosmic-settings

fix(popover): close popover when clicking outside of popover

---

src/app/mod.rs
src/widget/popover.rs

Fixes quirks with the context drawer and dialogs

fix(popover): add modal property for dialogs

---

src/widget/nav_bar.rs

nav_bar: allow setting close_icon and on_close

---

Cargo.toml
cosmic-config/Cargo.toml
cosmic-config/src/dbus.rs
cosmic-config/src/subscription.rs
examples/application/Cargo.toml

This subscription should try to reconnect to the settings-daemon after it restarts.

fix(cosmic-config): attempt to reconnect to the settings daemon

---

src/app/cosmic.rs
src/applet/mod.rs
src/theme/mod.rs

also converts applet to use preferred system theme

feat: allow preference for dark or light system theme

---

examples/cosmic/src/window/demo.rs
src/app/mod.rs
src/applet/mod.rs

I think these sizes still need to be approved by @pop-os/ux but they look good to me when testing with https://github.com/pop-os/cosmic-applets/pull/439

Feat applet text size

---

src/widget/button/widget.rs

This will enable us to use wgpu in cosmic-settings
closes #427

fix(image-button): fix rendering on wgpu

---

src/widget/segmented_button/widget.rs

Motion sometimes will make the dnd miss a target entity, so instead we track that no entity is hovered for the ongoing DnD, instead of clearing the DnD state.

fix: avoid completely clearing DnD state.

---

src/theme/style/iced.rs

Change inactive window header content opacity to 50%

---

cosmic-theme/src/output/gtk4_output.rs

This reverts commit 9f017de1fab4bb16606c6ae428bf6df2395e4c8b.

Revert "Theme GTK3/4 window controls to match COSMIC theme (#464)"

---

src/widget/mod.rs
src/widget/toaster/mod.rs

fix: toaster behind feature gate

---

README.md

Fixed broken link in README.md to point to documentation. 
Added code to add libcosmic as dependency for library instead of just a workspace. 
This makes the README.md more complete.
Please let me know if you need any changes as I am very flexible with my time.

Fixed broken link in README.md to point to docs. Added code to add libcosmic as dependency for lib.

---

src/widget/color_picker/mod.rs

fixes https://github.com/pop-os/libcosmic/issues/488

fix: draw color picker handle on top of gradient

---

src/app/cosmic.rs
src/keyboard_nav.rs
src/widget/text_input/input.rs

fix: widget unfocus on mouse click

---

src/app/mod.rs
src/widget/header_bar.rs

fixes #323 
depends https://github.com/pop-os/iced/pull/163

feat(header bar): double click to maximize

---

src/widget/text_input/input.rs

fixes https://github.com/pop-os/cosmic-launcher/issues/164?notification_referrer_id=NT_kwDOAuLU3rQxMTcxNjQyODcwNTo0ODQyMDA2Mg

fix: keep the cursor at the end if it previously when diffing

---

Cargo.toml
src/desktop.rs

We should never use heuristics to match desktop-entries.

Revert "fix: new matching algorithm for desktop entries"

---

examples/open-dialog/src/main.rs

The open-dialog is currently unable to open a file containing special characters.
This happens because the filename is taken from the url through `url.path()` which percent encodes special characters. When `File::open()` is called, the characters still are percent encoded, hence the file is not found.
This is fixed by using `url.to_file_path()` instead, which is fine because the url is checked before to be a file url. This operation can fail for multiple (probably rare in the real world) reasons and I am not sure how you want to handle them, hence I just called `unwrap()`.
`self.set_header_title(url.to_string());` on line 111 also prints the file with percent encoded characters at the top of the window. I think the header title should be set to the filepath **only if the file is …

Support special filenames in open-dialog example

---

src/widget/radio.rs

Reduce radio button size to match design

---

src/widget/popover.rs

This allows for the use of dropdowns in a popover, for example

fix(popover): implement overlay and remove use of refcell

---

Cargo.toml
examples/cosmic/src/main.rs
examples/cosmic/src/window/demo.rs
src/app/cosmic.rs
src/app/mod.rs
src/app/settings.rs
src/applet/mod.rs
src/config/mod.rs
src/font.rs
src/widget/button/icon.rs
src/widget/button/link.rs
src/widget/button/text.rs
src/widget/dropdown/menu/mod.rs
src/widget/dropdown/multi/menu.rs
src/widget/dropdown/multi/widget.rs
src/widget/dropdown/widget.rs
src/widget/segmented_button/widget.rs
src/widget/segmented_control.rs
src/widget/tab_bar.rs
src/widget/text.rs

This also adds an optimization for the dropdown widget which significantly improves rendering performance when there's a lot of dropdown selections.

Add font configuration capability

---

src/app/mod.rs
src/widget/context_drawer/widget.rs

Fixes #624, needed for cosmic-files dialog

feat(app): footer widget

---

src/widget/button/widget.rs

This should fix artifacts in the image button borders. I guess `with_layer` would be clipped before, but it needs to be given the viewport bounds now, or contents will be drawn outside of bounds.

fix: bounds for button

---

src/widget/button/widget.rs

This is a band-aid for a panic for accessibility tree creation, and another fix for the button rendering.

fix: button

---

src/widget/settings/section.rs

The api was stolen from Row And Column

Add add_maybe and extend on Section

---

src/widget/color_picker/mod.rs

It's a bit cursed because of how slider styling works now, but this works. The slider supports an on release handler, which fixes the hue slider not applying the color on release.

fix: color picker

---

src/app/mod.rs
src/theme/style/menu_bar.rs

Increases the border radius by 1.0 to prevent some corner artifacts, and makes the menu border radius the same.

Increase window border radius

---

src/app/mod.rs

fix: right padding for nav bar

---

src/widget/dialog.rs

This pr also only put a leading space when there was an actual element inserted in the column

feat: optional title on dialog

---

examples/context-menu/Cargo.toml
examples/context-menu/src/main.rs
examples/menu/Cargo.toml
examples/menu/src/main.rs
examples/nav-context/Cargo.toml
examples/nav-context/src/main.rs
src/widget/menu/menu_tree.rs

This PR implements icon support for menu items.

improv: icon support for menus

---

src/widget/context_drawer/overlay.rs

fix: don't apply drawer position as overlay translation

---

src/theme/style/iced.rs

Probably due to some import that were removed

fix compile for markdown feature

---

src/widget/dnd_destination.rs

Don't require `'static` child in `dnd_destination_for_data`

---

cosmic-config/src/dbus.rs

This seems to avoid an occasional race when cosmic session starts and apps are all started right when the theme is changing.

refactor: send initial config after watching for changes

---

src/theme/style/iced.rs

fix: impl combo_box::Catalog

---

src/process.rs

Allow using pipe on macOS when attempting to spawn a process.

fix: Support Spawning Processes on macOS

---

src/widget/text_input/input.rs

Fixes some common issues across cosmic applications.
- Fix clicks going through the text input to a mouse area behind it (ie: header bar)
- Fix clicks into the text input not placing a cursor at the end
- Fix cursor position of active text input being offset by layout
I will have more fixes soon for the editor not being enabled/disabled reliably on focus changes.
Closes #567

fix(text_input): fixing multiple issues

---

src/widget/autosize.rs
src/widget/button/widget.rs
src/widget/dropdown/widget.rs
src/widget/flex_row/widget.rs
src/widget/grid/widget.rs
src/widget/id_container.rs
src/widget/responsive_container.rs
src/widget/wayland/tooltip/widget.rs

I think something like this must be done for widgets to create popups and sub-surfaces at the correct position using the Layout. This fixes https://github.com/pop-os/cosmic-settings/issues/1067.

Virtual offset

---

examples/table-view/Cargo.toml
examples/table-view/src/main.rs
justfile
src/widget/mod.rs
src/widget/table/mod.rs
src/widget/table/model/category.rs
src/widget/table/model/entity.rs
src/widget/table/model/mod.rs
src/widget/table/model/selection.rs
src/widget/table/widget/compact.rs
src/widget/table/widget/mod.rs
src/widget/table/widget/standard.rs

This is a fresh pull request because of merge commits on the previous PR

feat: Add table widget

---

src/widget/text_input/input.rs

Compared with the current iced implementation of text_input, and made changes based on that to get better character input support.
Closes #702 
Closes #740

fix(text_input): support numpad keys

---

src/desktop.rs

This kind of filter is used by the app library

refactor: add only_show_in filter for loaded apps

---

src/widget/text_input/input.rs

RTL text will want to alight to the right, and will try to use all of an unbounded width in the input. It also tends to be offset in a negative direction.

fix: text input RTL panic

---

src/widget/calendar.rs

Added naive customizability for the first day of the week to the calendar-widget

Fixed TODO for first day of the week in the calendar widget

---

cosmic-config/src/dbus.rs

* Use `tracing::error!` in places where `eprintln!` was used
* Loop over errors and print seperately
* Print errors with `Display` rather than `Debug`
* Don't print errors that should be ignored
- Matches https://github.com/pop-os/libcosmic/pull/949, for same reasons.
With this, and the previous change, cosmic-panel no longer spams a bunch of config errors from different applets on start.

fix(cosmic-config): Fixes for error printing

---

Cargo.toml
examples/multi-window/Cargo.toml
src/app/cosmic.rs
src/app/mod.rs
src/core.rs
src/surface/action.rs
src/surface/mod.rs
src/theme/style/iced.rs
src/widget/header_bar.rs

requires https://github.com/pop-os/iced/pull/242

feat(wayland): corner-radius protocol support

---

src/widget/about.rs

Aligns to designs.
Also reduces code duplication a bit.

[About] Styling fixes
